[manager]
sort_by = "mtime"
sort_sensitive = true
sort_reverse = true
sort_dir_first = true
show_symling = true

scrolloff = 20

[opener]
edit = [
  { run = 'nvim "$@"', block = true },
]
play = [
  { run = 'xdg-open "$@"', orphan = true, for = "unix" },
]
open = [
  { run = 'xdg-open "$@"', desc = "Open" },
]
